# Generated by Django 3.2.13 on 2022-06-06 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('other_names', models.TextField()),
                ('type', models.CharField(choices=[('0', 'Combination Product'), ('1', 'Device'), ('2', 'Biological'), ('3', 'Radiation'), ('4', 'Other'), ('5', 'Genetic'), ('6', 'Drug'), ('7', 'Procedure'), ('8', 'Dietary Supplement'), ('9', 'Diagnostic Test'), ('10', 'Behavioral')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Biomarker',
                'verbose_name_plural': 'Biomarkers',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('other_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('alpha3', models.CharField(max_length=3)),
                ('alpha2', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField()),
                ('text', models.TextField()),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('posted_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sponser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('subscription_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdatesLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_counts', models.SmallIntegerField()),
                ('udpate_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.CharField(max_length=11, unique=True, verbose_name='NCT ID')),
                ('phase', models.CharField(blank=True, choices=[('N', 'No Phase'), ('1', 'Phase 1'), ('2', 'Phase 2'), ('3', 'Phase 3'), ('12', 'Phase 1 | Phase 2'), ('23', 'Phase 2 | Phase 3'), ('4', 'Phase 4')], max_length=2)),
                ('status', models.CharField(choices=[('A', 'Active, not recruiting'), ('C', 'Completed'), ('E', 'Enrolling by invitation'), ('N', 'Not yet recruiting'), ('R', 'Recruiting'), ('S', 'Suspended'), ('T', 'Terminated'), ('U', 'Unknown status'), ('W', 'Withdrawn')], max_length=1)),
                ('design_primary_purpose', models.CharField(choices=[('T', 'Treatment'), ('P', 'Prevention'), ('D', 'Diagnostic'), ('U', 'Supportive Care'), ('C', 'Screening'), ('H', 'Health Services Research'), ('B', 'Basic Science'), ('O', 'Other')], max_length=1)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('first_posted', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('first_start_date', models.DateField(blank=True, null=True, verbose_name='Start Date at First Registration')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('first_end_date', models.DateField(blank=True, null=True, verbose_name='End Date at First Registration')),
                ('primary_completion', models.DateField(blank=True, null=True)),
                ('first_primary_completion', models.DateField(blank=True, null=True, verbose_name='Primary Completion Date at First Registration')),
                ('last_update', models.DateField(blank=True, null=True)),
                ('study_duration', models.IntegerField(blank=True, null=True)),
                ('primary_outcome', models.TextField(blank=True, null=True, verbose_name='Primary Outcome Measure')),
                ('secondary_outcome', models.TextField(blank=True, null=True, verbose_name='Secondary Outcome Measures')),
                ('other_outcome', models.TextField(blank=True, null=True, verbose_name='Other Outcome Measures')),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('treatment_duration', models.CharField(blank=True, max_length=500, null=True)),
                ('treatment_weeks', models.FloatField(blank=True, null=True)),
                ('treatment_days', models.IntegerField(blank=True, null=True)),
                ('enroll_number', models.IntegerField(blank=True, null=True)),
                ('arms_number', models.IntegerField(blank=True, null=True)),
                ('per_arm', models.IntegerField(blank=True, null=True)),
                ('funder_type', models.CharField(choices=[('N', 'U.S. National Institutes of Health'), ('F', 'Federal Agencies'), ('I', 'Industry'), ('G', 'Other_Gov'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(blank=True, choices=[('1', 'US ONLY'), ('2', 'NON-US ONLY'), ('3', 'BOTH US & NON-US')], max_length=1, null=True)),
                ('location_str', models.TextField(blank=True, null=True, verbose_name='Locations')),
                ('num_sites', models.IntegerField(blank=True, null=True)),
                ('min_age', models.CharField(blank=True, max_length=11, null=True)),
                ('max_age', models.CharField(blank=True, max_length=11, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('agent', models.ManyToManyField(blank=True, to='panels.Agent', verbose_name='Agents')),
                ('biomarker', models.ManyToManyField(blank=True, to='panels.Biomarker', verbose_name='Biomarkers')),
                ('condition', models.ManyToManyField(blank=True, to='panels.Condition', verbose_name='Conditions')),
                ('countries', models.ManyToManyField(blank=True, to='panels.Country', verbose_name='Countries')),
                ('sponsor', models.ManyToManyField(blank=True, to='panels.Sponser', verbose_name='Sponsors')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTrial',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nct_id', models.CharField(db_index=True, max_length=11, verbose_name='NCT ID')),
                ('phase', models.CharField(blank=True, choices=[('N', 'No Phase'), ('1', 'Phase 1'), ('2', 'Phase 2'), ('3', 'Phase 3'), ('12', 'Phase 1 | Phase 2'), ('23', 'Phase 2 | Phase 3'), ('4', 'Phase 4')], max_length=2)),
                ('status', models.CharField(choices=[('A', 'Active, not recruiting'), ('C', 'Completed'), ('E', 'Enrolling by invitation'), ('N', 'Not yet recruiting'), ('R', 'Recruiting'), ('S', 'Suspended'), ('T', 'Terminated'), ('U', 'Unknown status'), ('W', 'Withdrawn')], max_length=1)),
                ('design_primary_purpose', models.CharField(choices=[('T', 'Treatment'), ('P', 'Prevention'), ('D', 'Diagnostic'), ('U', 'Supportive Care'), ('C', 'Screening'), ('H', 'Health Services Research'), ('B', 'Basic Science'), ('O', 'Other')], max_length=1)),
                ('protocol', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('first_posted', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('first_start_date', models.DateField(blank=True, null=True, verbose_name='Start Date at First Registration')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('first_end_date', models.DateField(blank=True, null=True, verbose_name='End Date at First Registration')),
                ('primary_completion', models.DateField(blank=True, null=True)),
                ('first_primary_completion', models.DateField(blank=True, null=True, verbose_name='Primary Completion Date at First Registration')),
                ('last_update', models.DateField(blank=True, null=True)),
                ('study_duration', models.IntegerField(blank=True, null=True)),
                ('primary_outcome', models.TextField(blank=True, null=True, verbose_name='Primary Outcome Measure')),
                ('secondary_outcome', models.TextField(blank=True, null=True, verbose_name='Secondary Outcome Measures')),
                ('other_outcome', models.TextField(blank=True, null=True, verbose_name='Other Outcome Measures')),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('treatment_duration', models.CharField(blank=True, max_length=500, null=True)),
                ('treatment_weeks', models.FloatField(blank=True, null=True)),
                ('treatment_days', models.IntegerField(blank=True, null=True)),
                ('enroll_number', models.IntegerField(blank=True, null=True)),
                ('arms_number', models.IntegerField(blank=True, null=True)),
                ('per_arm', models.IntegerField(blank=True, null=True)),
                ('funder_type', models.CharField(choices=[('N', 'U.S. National Institutes of Health'), ('F', 'Federal Agencies'), ('I', 'Industry'), ('G', 'Other_Gov'), ('O', 'Other')], max_length=1)),
                ('location', models.CharField(blank=True, choices=[('1', 'US ONLY'), ('2', 'NON-US ONLY'), ('3', 'BOTH US & NON-US')], max_length=1, null=True)),
                ('location_str', models.TextField(blank=True, null=True, verbose_name='Locations')),
                ('num_sites', models.IntegerField(blank=True, null=True)),
                ('min_age', models.CharField(blank=True, max_length=11, null=True)),
                ('max_age', models.CharField(blank=True, max_length=11, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical trial',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
