# Generated by Django 3.2.13 on 2022-06-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sponser',
            new_name='Sponsor',
        ),
        migrations.AddField(
            model_name='historicaltrial',
            name='brief_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltrial',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='brief_summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
