# Generated by Django 3.2.13 on 2022-06-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_auto_20220610_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrial',
            name='design_primary_purpose',
            field=models.CharField(choices=[('T', 'Treatment'), ('P', 'Prevention'), ('D', 'Diagnostic'), ('U', 'Supportive Care'), ('C', 'Screening'), ('H', 'Health Services Research'), ('B', 'Basic Science'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='design_primary_purpose',
            field=models.CharField(choices=[('T', 'Treatment'), ('P', 'Prevention'), ('D', 'Diagnostic'), ('U', 'Supportive Care'), ('C', 'Screening'), ('H', 'Health Services Research'), ('B', 'Basic Science'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
