# Generated by Django 3.2.13 on 2022-06-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_auto_20220610_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrial',
            name='funder_type',
            field=models.CharField(choices=[('N', 'U.S. National Institutes of Health'), ('F', 'Federal Agencies'), ('I', 'Industry'), ('G', 'Other_Gov'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trial',
            name='funder_type',
            field=models.CharField(choices=[('N', 'U.S. National Institutes of Health'), ('F', 'Federal Agencies'), ('I', 'Industry'), ('G', 'Other_Gov'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
