# Generated by Django 3.2.13 on 2022-10-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0004_auto_20220610_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrial',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historicaltrial',
            name='sample',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trial',
            name='sample',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltrial',
            name='phase',
            field=models.CharField(blank=True, choices=[('N', 'No Phase'), ('E', 'Early 1'), ('1', 'Phase 1'), ('2', 'Phase 2'), ('3', 'Phase 3'), ('12', 'Phase 1 | Phase 2'), ('23', 'Phase 2 | Phase 3'), ('4', 'Phase 4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='trial',
            name='condition',
            field=models.ManyToManyField(blank=True, to='panels.Condition', verbose_name='Conditions/Diseases'),
        ),
        migrations.AlterField(
            model_name='trial',
            name='phase',
            field=models.CharField(blank=True, choices=[('N', 'No Phase'), ('E', 'Early 1'), ('1', 'Phase 1'), ('2', 'Phase 2'), ('3', 'Phase 3'), ('12', 'Phase 1 | Phase 2'), ('23', 'Phase 2 | Phase 3'), ('4', 'Phase 4')], max_length=2),
        ),
    ]
